Repository apache/incubator-kie-drools, pull requests merged in 2023-02, with the labels that each got.

#4975 Fix setup-branch job
  .ci/jenkins/project/Jenkinsfile.setup-branch
Labels: backport-8.34.x

#4971 [7.x] [DROOLS-7331] ResultSetGeneratorTest fails with JDK8
  drools-templates/pom.xml
Labels: backport-7.67.x, backport-7.67.x-blue

#4978 RHDM-1957 DROOLS-7267 DMN extend rule to catch non-normalized named elements
  kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/util/Msg.java
  kie-dmn/kie-dmn-legacy-tests/src/test/java/org/kie/dmn/legacy/tests/validation/v1_1/ValidatorTest.java
  kie-dmn/kie-dmn-validation/src/main/resources/org/kie/dmn/validation/DMNv1x/dmn-validation-rules.drl
  kie-dmn/kie-dmn-validation/src/test/java/org/kie/dmn/validation/ValidatorTest.java
  kie-dmn/kie-dmn-validation/src/test/resources/org/kie/dmn/validation/NAME_NOT_NORMALIZED.dmn
Labels: backport-7.67.x, backport-7.67.x-blue

#5007 DSL Config: Update Git credentials
  .ci/jenkins/config/branch.yaml
Labels: backport-8.34.x

#4996 KOGITO-8667 Reorganize GHA
  .github/workflows/kogito-examples-pr.yml
  .github/workflows/optaplanner-pr.yml
  .github/workflows/pr-downstream-full.yml
  .github/workflows/pr-downstream.yml
  .github/workflows/pr-drools-docs.yml
  .github/workflows/pr-drools.yml
  .github/workflows/pr-jenkins.yml
  .github/workflows/pr-optaplanner.yml
Labels: skip-ci

#5010 DSL branch Config: Revert quarkus credentials
  .ci/jenkins/config/branch.yaml
Labels: backport-8.34.x

#5017 removed post-release-job
  .ci/jenkins/dsl/jobs.groovy
Labels: backport-8.34.x
