Repository apache/incubator-kie-drools, pull requests merged in 2023-08, with the labels that each got.

#5419 Ignore enforcer rules if stream is not 8
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
Labels: backport-9.42.x

#5422 [9.42.x] Correct deploy pipeline
  .ci/jenkins/Jenkinsfile.deploy
Labels: backport-main

#5395 Bump h2 from 1.4.197 to 2.2.220
  drools-persistence/drools-persistence-jpa/pom.xml
  drools-traits/pom.xml
  kie-test-util/src/main/java/org/kie/test/util/db/PersistenceUtil.java
Labels: backport-7.67.x, backport-7.67.x-blue

#5431 [9.42.x] Correct promote pipeline
  .ci/jenkins/Jenkinsfile.promote
Labels: backport-main
